name: Run Playwright Tests in Docker
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - '**'         
  pull_request:
    types: [opened] 

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy

    env:
      HOME: /root
      BASE_URL: ${{ secrets.BASE_URL }}
      HTTP_CREDENTIALS_USERNAME: ${{ secrets.HTTP_CREDENTIALS_USERNAME }}
      HTTP_CREDENTIALS_PASSWORD: ${{ secrets.HTTP_CREDENTIALS_PASSWORD }}
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx playwright test tests/task24.spec.js --project=firefox